### ISSUE TITLE
[PE-D] Failure to delete multiple assessments with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#169]
![image.png](https://raw.githubusercontent.com/kairoskoh/ped/main/files/ca6d1394-f8d5-4eda-a864-e6032ba6790e.png)

As seen above, only one of the duplicated PEs are deleted.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kairoskoh/ped#6

**Comment by hozhenhong99** [comment]
resolved
