### ISSUE TITLE
[PE-D] Incorrect integer overflow error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#170]
![Screenshot 2021-10-29 171159.png](https://raw.githubusercontent.com/vincentlauhl/ped/main/files/25ef9447-18a2-4fac-8cbe-b3ebbdb0d1e5.png)

The error message does not match the integer overflow error

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: vincentlauhl/ped#3

**Comment by jon-the-melon** [comment]
probably overflowed into a negative...
