### ISSUE TITLE
[PE-D] Fault command: set_marks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#171]
![image.png](https://raw.githubusercontent.com/kairoskoh/ped/main/files/41bbb036-c179-49d3-b63b-aa4d54fdf6a0.png)

As seen above, the commands incurs an exception.

![image.png](https://raw.githubusercontent.com/kairoskoh/ped/main/files/d8e25983-7473-4903-a6af-0671c63be655.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kairoskoh/ped#7

**Comment by jon-the-melon** [comment]
updated ug to reflect correct command.
