### ISSUE TITLE
[PE-D] Faulty Command: edit_mark

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#176]
![image.png](https://raw.githubusercontent.com/kairoskoh/ped/main/files/c2224ee1-240d-4dba-bb70-2b4cb77d40b9.png)

Since there is nofo way to create marks, code is unable to use this command: edit_mark.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kairoskoh/ped#8

**Comment by jon-the-melon** [comment]
error in ug caused user to use wrong command 'set_marks'
