### ISSUE TITLE
[PE-D] Does not accept case sensitive input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#177]
![image.png](https://raw.githubusercontent.com/thaddyyz/ped/main/files/932d59cb-5abd-48d4-91b9-0aeac498cb82.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: thaddyyz/ped#1

**Comment by leyondlee** [comment]
Intended
