### ISSUE TITLE
[PE-D] Faulty command: average_marks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#182]
![image.png](https://raw.githubusercontent.com/kairoskoh/ped/main/files/c2224ee1-240d-4dba-bb70-2b4cb77d40b9.png)

Since there is no way to create marks, code is unable to use this command: average_marks.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kairoskoh/ped#11

**Comment by jon-the-melon** [comment]
error in ug caused user to use wrong command 'set_marks'
