### ISSUE TITLE
[PE-D] Students can have the same Student number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#189]
![image.png](https://raw.githubusercontent.com/thaddyyz/ped/main/files/0693647c-d4b4-4354-a7a2-171d5e7f1ac1.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: thaddyyz/ped#8

**Comment by hozhenhong99** [comment]
resolved
