### ISSUE TITLE
[PE-D] No Visuals in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#190]
![image.png](https://raw.githubusercontent.com/thaddyyz/ped/main/files/d9dcb266-7501-4d5a-81a0-c602b7461864.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: thaddyyz/ped#9

**Comment by hozhenhong99** [comment]
resolved
