### ISSUE TITLE
[PE-D] Commands are complex

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#192]
![image.png](https://raw.githubusercontent.com/ZenoNexus/ped/main/files/0661a788-30b3-4b9c-a142-90020d86c0ad.png)

Due to the long line of commands, it is possible and likely optimal to group the commands of similar type together.

For example, if i am interested in adding something, it could be optimised to "add" + identifier tag (e.g. -m for module, -s for student, -a for assessment, etc.) 

This problem also causes issues because some commands are plural while others are not, it might be better to make them all standardized. At the end of the day, as a frequent user I do not want to remember whether it should be "average_mark" or "average_marks", "median_mark" or "median_marks"

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ZenoNexus/ped#5

**Comment by hozhenhong99** [comment]
jon to change average mark

**Comment by hozhenhong99** [comment]
fixed
