### ISSUE TITLE
[PE-D] set_marks function does not work despite following the input convention

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-3/tp#198]
![image.png](https://raw.githubusercontent.com/thaddyyz/ped/main/files/85880bc4-9e15-443a-a68a-af1d4a31f538.png)

![image.png](https://raw.githubusercontent.com/thaddyyz/ped/main/files/6c71cbd4-187d-4d41-adaa-80cad0d38863.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: thaddyyz/ped#13

**Comment by jon-the-melon** [comment]
updated ug to reflect correct command format
