### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by rachelkeh** [AY2122S1-CS2113T-F12-3/tp#249]
![image](https://user-images.githubusercontent.com/70307497/140609426-99a545f9-d7d7-4699-a7f5-c6e4055a13c6.png)

**Comment by leyondlee** [comment]
1. Are there 2 assessments when you run `list_assessment`?
2. Also can remove "the"?

**Comment by rachelkeh** [comment]
1. Nope idts, I don't allow any assessments with duplicate names. I think it's like this because I input in 3dp but we are only displaying 2dp. The value inside the program doesn't get affected. I'll prolly have to add a note inside the UG for this
2. Ok I'll remove now
