### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by rachelkeh** [AY2122S1-CS2113T-F12-3/tp#257]
<img width="645" alt="2" src="https://user-images.githubusercontent.com/70307497/140614783-abde09ae-2400-47e6-a9e3-b00ec43f1891.PNG">
the exception msg's a little weird (?)

**Comment by leyondlee** [comment]
Because `n/OP2` is not recognized as a argument itself, the string is considered part of `c/...`. So for `c/`, it is reading the value as `CS2101-C03 n/OP2`, which contains an invalid character `/`.

**Comment by leyondlee** [comment]
Should be `a/`
